"""empty message

Revision ID: 1050e313e30e
Revises: a6f36134f54e
Create Date: 2023-05-24 21:06:55.892198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1050e313e30e'
down_revision = 'a6f36134f54e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
